services:
  main-app:
    image: ghcr.io/d-led/independent_liveview_components_experiment/main-app:latest
    build:
      context: main_app
    ports:
      - "4000:4000"
    hostname: main.internal
    environment:
      - RELEASE_COOKIE=local-1mIJ1VsA9
      - LOG_LEVEL=debug
      - SECRET_KEY_BASE=$${SECRET_KEY_BASE:local-A6+1M8BjONKQQJcI/CwwvemkjQgPnVw56UJW13QXip4+F0krSGWlmUyAqHQF9not}

  global-service:
    image: ghcr.io/d-led/independent_liveview_components_experiment/global-service:latest
    build:
      context: global_service
    ports:
      - "4001:4000"
    hostname: global.internal
    environment:
      - RELEASE_COOKIE=local-1mIJ1VsA9
      - LOG_LEVEL=debug
      - ERLANG_SEED_NODES=main_app@main.internal
      - SECRET_KEY_BASE=$${SECRET_KEY_BASE:local-Hc7PL5+zLbzrIwYdRHF8bcdUa8WCnAKlOfwiUHZdjqP1gZXn+MvkDH/Y6fD0+7kU}
    depends_on:
      - main-app

  private-service:
    image: ghcr.io/d-led/independent_liveview_components_experiment/private-service:latest
    build:
      context: private_service
    ports:
      - "4002:4000"
    hostname: private.internal
    environment:
      - RELEASE_COOKIE=local-1mIJ1VsA9
      - LOG_LEVEL=debug
      - ERLANG_SEED_NODES=main_app@main.internal
      - SECRET_KEY_BASE=$${SECRET_KEY_BASE:local-w2JUXE9yXYRqkz092hjJAbSTcQAmm/OfHiQNVbDLHFSen8uAxzyOvLA6c3yxYYmu}
    depends_on:
      - main-app
