version: "0.5"

# https://f1bonacc1.github.io/process-compose/
# process-compose

log_location: processes.log
log_level: debug

processes:
  main:
    command: "mix setup && elixir --name main_app@127.0.0.1 -S mix phx.server"
    working_dir: "./main_app"
    environment:
      - "PORT=4000"

  global:
    command: "mix setup && elixir --name global_service@127.0.0.1 -S mix phx.server"
    working_dir: "./global_service"
    environment:
      - "PORT=4001"

  private:
    command: "mix setup && elixir --name private_service@127.0.0.1 -S mix phx.server"
    working_dir: "./private_service"
    environment:
      - "PORT=4002"
